### PR TITLE
feat: use a safe typed routeur

### PR DESCRIPTION
**Pull request by Tchoupinax**
Hey,

Suggestion about using a type safe router in react. I did not find the way yet to correctly plug the ErrorPage, as I might miss knowledges about React

### CODE REVIEW

**Comment by evoxmusic** [comment]
I didn't know `@swan-io/chicane` - what's the value over the router I used?

**Comment by Tchoupinax** [comment]
Your router are safe typed (name, params), it works well with the `ts-pattern` lib to do matching model that improve the DX

image

**Comment by Tchoupinax** [comment]
Frontend is not my expertise so I won't be super helpful on this. As far as I understand, this library brings strong types that are very useful when you app starts to grow. I let you decide if you want to give a try!

**Comment by Tchoupinax** [comment]
Reopen the day when I will manage this better! :)

**Pull request closed without merging**
